spring.application.name=temp-paste

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}

app.blacklist.path=${BLACKLIST_PATH}